### ISSUE TITLE
스프링부트 토이 프로젝트

### ISSUE THREAD

**Issue by tletle7102** [tletle7102/toyprj1#1]
# Todo

- [ ] 프로젝트 생성
	- [x] jdk 이해
	- [x] build에 대해서 intelliJ와 gradle 차이
	- [x] 새 프로젝트 생성
	- [x] github repository 생성 및 연결
	- [x] readme.md작성
	- [ ] git issue 생성(예정)
	- [ ] git PR(pull request) 생성
- [ ] 의존성 추가
	- [ ] springboot starter
	- [ ] lombok
	- [ ] db
- [ ] 사용자 관리 기능(User 도메인)
	- [ ] data
	- [ ] service
	- [ ] repository
	- [ ] test
- [ ] 회원 관리 기능(Member 도메인)
	- [ ] data
	- [ ] service
	- [ ] repository
	- [ ] test
- [ ] 게시판 관리 기능(Board 도메인)
	- [ ] data
	- [ ] service
	- [ ] repository
	- [ ] test
- [ ] 댓글 관리 기능(Comment 도메인)
	- [ ] data
	- [ ] service
	- [ ] repository
	- [ ] test
- [ ] 서버접속
	- [ ] ubuntu 이해
	- [ ] 리눅스 용어 이해
	- [ ] ssh 이해
- [ ] (시간 여유가 있을 시) CI/CD pipeline 구축

**Comment by tletle7102** [comment]
`프로젝트 생성` 중에 `github repository 생성 및 연결`을 하면서 원하지 않는 파일이 변경대상에 추가되어 커밋되었음. 
이에 대해 다음 프로젝트에서는 신경써서 처리할 예정.
